-- encoding: UTF-8

------------------------------------------------
-- Emoji 输入法
-- 版本: 0.1
-- 作者: LIU Dongyuan <liu.dongyuan@gmail.com>
-- 作者主页：https://github.com/xhacker
------------------------------------------------

-- Courtesy to http://www.hskhsk.com/2/post/2013/06/emoji-with-ios-pinyin-keyboard.html
-- TODO: full pinyin to emoji list.
PINYIN_EMOJI = {
  ["bangqiu"] = {"⚾"},
  ["baobing"] = {"🍧"},
  ["bi"] = {"🆚"},
  ["bijini"] = {"👙"},
  ["bizi"] = {"👃"},
  ["bolang"] = {"🌊"},
  ["caihong"] = {"🌈"},
  ["cangshu"] = {"🐹"},
  ["caomei"] = {"🍓"},
  ["cesuo"] = {"🚽"},
  ["cha"] = {"☕"},
  ["chenshan"] = {"👕"},
  ["chuan"] = {"🚢"},
  ["chuzuche"] = {"🚕"},
  ["dangao"] = {"🍰", "🎂"},
  ["dianhua"] = {"☎"},
  ["diannao"] = {"💻"},
  ["dianshi"] = {"📺"},
  ["dianying"] = {"🎬"},
  ["erduo"] = {"👂"},
  ["fanchuan"] = {"⛵"},
  ["fanqie"] = {"🍅"},
  ["feiji"] = {"✈"},
  ["ganlanqiu"] = {"🏈"},
  ["gaoerfu"] = {"⛳"},
  ["ge"] = {"🈹"},
  ["gonggongqiche"] = {"🚌"},
  ["guangbo"] = {"📢"},
  ["guangpan"] = {"💿", "📀"},
  ["guoshanche"] = {"🎢"},
  ["haibei"] = {"🐚"},
  ["haitun"] = {"🐬"},
  ["hanbaobao"] = {"🍔"},
  ["hao"] = {"👌", "🆗"},
  ["hou"] = {"🐒"},
  ["huangxin"] = {"💛"},
  ["huo"] = {"🔥"},
  ["huoche"] = {"🚚"},
  ["huoche"] = {"🚄", "🚅"},
  ["huojian"] = {"🚀"},
  ["ji"] = {"🐔"},
  ["jiewen"] = {"💏"},
  ["jingche"] = {"🚓"},
  ["jingyu"] = {"🐳"},
  ["jita"] = {"🎸"},
  ["jiuhuche"] = {"🚑"},
  ["jiweijiu"] = {"🍸"},
  ["kaixin"] = {"😄"},
  ["kong"] = {"🈳"},
  ["kouhong"] = {"💄"},
  ["kuaiting"] = {"🚤"},
  ["kuqi"] = {"😢", "😭"},
  ["laba"] = {"🎺"},
  ["lang"] = {"🐺"},
  ["lanqiu"] = {"🏀"},
  ["lanxin"] = {"💙"},
  ["laohu"] = {"🐯"},
  ["laoren"] = {"👴"},
  ["laoshu"] = {"🐭"},
  ["liangxie"] = {"👡"},
  ["limao"] = {"🎩", "👒"},
  ["luotuo"] = {"🐫"},
  ["luxiangdai"] = {"📼"},
  ["lvcha"] = {"🍵"},
  ["lvxin"] = {"💚"},
  ["ma"] = {"🐴", "🐎"},
  ["man"] = {"🈵"},
  ["mao"] = {"🐱"},
  ["maomaochong"] = {"🐛"},
  ["meigui"] = {"🌹"},
  ["mianbao"] = {"🍞"},
  ["mifan"] = {"🍚"},
  ["motianlun"] = {"🎡"},
  ["muniu"] = {"🐮"},
  ["nangua"] = {"🎃"},
  ["nanhaizi"] = {"👦"},
  ["nanren"] = {"👨"},
  ["niao"] = {"🐦"},
  ["nvhaizi"] = {"👧"},
  ["nvren"] = {"👩"},
  ["penshuichi"] = {"⛲"},
  ["pijiu"] = {"🍺", "🍻"},
  ["pingguo"] = {"🍎"},
  ["qian"] = {"💰"},
  ["qiche"] = {"🚗"},
  ["qie"] = {"🐧"},
  ["qiezi"] = {"🍆"},
  ["qingwa"] = {"🐸"},
  ["qinqin"] = {"😘", "😚"},
  ["qunzi"] = {"👗"},
  ["sakesifeng"] = {"🎷"},
  ["shandian"] = {"⚡"},
  ["shangmian"] = {"☝"},
  ["she"] = {"🐍"},
  ["sheyingji"] = {"🎥"},
  ["shou"] = {"👐", "👋"},
  ["shubao"] = {"🎒"},
  ["shudaixiong"] = {"🐨"},
  ["shuiguo"] = {"🍊", "🍉"},
  ["shuijiao"] = {"💤", "😪"},
  ["shutiao"] = {"🍟"},
  ["taiqiu"] = {"🎱"},
  ["taiyang"] = {"☀"},
  ["tangmian"] = {"🍜"},
  ["tianqi"] = {"☔", "☁"},
  ["tiaowu"] = {"💃"},
  ["tuzi"] = {"🐰"},
  ["wangqiu"] = {"🎾"},
  ["wu"] = {"🈚"},
  ["xiamian"] = {"👇"},
  ["xiang"] = {"🐘"},
  ["xiangji"] = {"📷"},
  ["xiangrikui"] = {"🌻"},
  ["xianrenzhang"] = {"🌵"},
  ["xiaofangche"] = {"🚒"},
  ["xiaogou"] = {"🐶"},
  ["xiaoji"] = {"🐤"},
  ["xiaozhu"] = {"🐷"},
  ["xie"] = {"👟", "👠"},
  ["xigua"] = {"🍉"},
  ["xihuan"] = {"😍", "💓"},
  ["xin"] = {"❤", "🆕"},
  ["xinsui"] = {"💔"},
  ["xiong"] = {"🐻"},
  ["xueren"] = {"⛄"},
  ["yang"] = {"🐑"},
  ["yanlian"] = {"👀"},
  ["yezi"] = {"🍃"},
  ["yin"] = {"🈺"},
  ["yinfu"] = {"🎵", "🎶"},
  ["yinyue"] = {"🎵", "🎷"},
  ["you"] = {"🈶"},
  ["youbian"] = {"👉"},
  ["youyong"] = {"🏊"},
  ["yu"] = {"🐠", "🐟"},
  ["yue"] = {"🈷"},
  ["yueliang"] = {"🌙"},
  ["yujinxiang"] = {"🌷"},
  ["yusan"] = {"🌂", "☔"},
  ["zhangyu"] = {"🐙"},
  ["zhu"] = {"🐗"},
  ["zixin"] = {"💜"},
  ["zixingche"] = {"🚲"},
  ["ziyounvshen"] = {"🗽"},
  ["zuanshi"] = {"💎"},
  ["zui"] = {"👄"},
  ["zuobian"] = {"👈"},
  ["zuqiu"] = {"⚽"},
}

function emojiInput(arg)
  return PINYIN_EMOJI[arg]
end

------------

ime.register_command("em", "emojiInput", "Emoji", "none", "请输入 Emoji 描述")
